spring.application.name=bot

telegram.bot.username=${TELEGRAMBOT_USERNAME}
telegram.bot.token=${TELEGRAMBOT_TOKEN}
rapidapi.key=${RAPIDAPI_KEY}

spring.datasource.url=jdbc:h2:file:./data/testdb;AUTO_SERVER=TRUE
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=mainMF
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=create-drop
spring.main.web-application-type=servlet
spring.h2.console.enabled=true

spring.jpa.defer-datasource-initialization=true