spring.application.name=bot

telegram.bot.username=@Job4pplicationBot
telegram.bot.token=8803738683:AAG1Nbngs9kniVnIOaX9JQbfbH7rphK4XSk
rapidapi.key=85a0cff5bbmshc629daebe26522cp1bdbb0jsnc2f43a8bf1b6

spring.datasource.url=jdbc:h2:file:./data/testdb;AUTO_SERVER=TRUE
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=mainMF
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=create-drop
spring.main.web-application-type=servlet
spring.h2.console.enabled=true

spring.jpa.defer-datasource-initialization=true